### ISSUE TITLE
"Long running async.py" in the example cannot run normally [BUG]

### ISSUE THREAD

**Issue by xjaslkjkalsd** [lexiforest/curl_cffi#270]
```python
"""
WIP: this has not been implemented yet.
"""
import asyncio
from curl_cffi import requests


async def on_message(ws, message):
    print(message)


async def on_error(ws, error):
    print(error)


async def on_open(ws):
    print("For websockets, you need to set $wss_proxy environment variable!\n"
          "$https_proxy will not work!")
    print(">>> Websocket open!")


async def on_close(ws):
    print("<<< Websocket closed!")


async def main():
    async with requests.AsyncSession() as s:
        ws = await s.ws_connect(
            "wss://api.gemini.com/v1/marketdata/BTCUSD",
            on_open=on_open,
            on_close=on_close,
            on_message=on_message,
            on_error=on_error,
        )
        ws.run_forever()


asyncio.run(main())
```

Terminal error
```bash
Traceback (most recent call last):
  File "/Users/baobao/MyDesktop/python/func-proxy/test.py", line 38, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.10/3.10.13_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.13_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/baobao/MyDesktop/python/func-proxy/test.py", line 28, in main
    ws = await s.ws_connect(
  File "/opt/homebrew/lib/python3.10/site-packages/curl_cffi/requests/session.py", line 978, in ws_connect
    self._set_curl_options(curl, "GET", url, *args, **kwargs)
TypeError: BaseSession._set_curl_options() got an unexpected keyword argument 'on_open'
```

**Comment by yifeikong** [comment]
The websocket support is still experimental, the sync api is more usable.
