### ISSUE TITLE
[BUG]在curl_options中修改HTTPHEADER 报类型错误

### ISSUE THREAD

**Issue by mrzcpoGit** [lexiforest/curl_cffi#363]
```
#方法1
response = requests.post(args.url,headers=headers,impersonate=args.finger,data=bodyString,proxy=args.proxy,timeout=args.timeout,allow_redirects=args.allow_redirects,verify=False,default_headers=False,
            curl_options={
                CurlOpt.HTTPHEADER:tuple(["Content-Type: application/json; charset=UTF-8","Host: xxx.com"])
            })

#方法2
response = requests.post(args.url,headers=headers,impersonate=args.finger,data=bodyString,proxy=args.proxy,timeout=args.timeout,allow_redirects=args.allow_redirects,verify=False,default_headers=False,
            curl_options={
                CurlOpt.HTTPHEADER:["Content-Type: application/json; charset=UTF-8","Host: xxx.com"]
            })
```

requests.post 自带的设置headers的功能会限制   Content-Type为application/json或者application/x-www-form-urlencoded，由于服务器端只接受application/json; charset=UTF-8，我想通过curl_options设置header，但是我尝试了以上两种方式之后均报同样的错误 

```
Traceback (most recent call last):

  File "tls_req.py", line 12, in <module>

  File "<string>", line 104, in <module>

  File "<string>", line 90, in main

  File "curl_cffi\requests\__init__.py", line 125, in request

  File "curl_cffi\requests\session.py", line 900, in request

  File "curl_cffi\requests\session.py", line 618, in _set_curl_options

  File "curl_cffi\curl.py", line 202, in setopt

TypeError: initializer for ctype 'char *' must be a bytes or list or tuple, not str

[15712] Failed to execute script 'tls_req' due to unhandled exception!
```

**Comment by mrzcpoGit** [comment]
谢谢！我不太懂py，见笑了

不用 headers 是因设置Content-Type之后 会被覆盖为 application/json 或者 application/x-www-form-urlencoded
可能是因为session.py中410行处  先设置了headers 之后修改了Content-Type。可能需要个判断，在设置content-Type之前判断传入的headers中是否包含content-type

![1722938096859](https://github.com/user-attachments/assets/44ac97e7-66e6-4c07-9d63-34cf9bd29b4a)

**Comment by yifeikong** [comment]
有道理，谢谢你的反馈，有空了改下。

**Comment by lexiforest** [comment]
This should be fixed in 0.7.3, `Content-Type` will no longer be overwritten if provided.
