### ISSUE TITLE
[BUG] Unsupported ctypes for getinfo to work

### ISSUE THREAD

**Issue by ringus1** [lexiforest/curl_cffi#407]
**Describe the bug**
Some `CurlInfo` constants can't be retrieved seemingly because types are not supported, such as `curl_off_t`.

Raw CURL command
```sh
> curl --compressed -so /dev/null http://www.whatsmyip.org/http-compression-test/ -w '%{size_download}'
256
```
Python attempt
```python
> import curl_cffi

> curl = curl_cffi.Curl()
> curl.setopt(curl_cffi.CurlOpt.URL, "http://www.whatsmyip.org/http-compression-test/")
> curl.setopt(curl_cffi.CurlOpt.ACCEPT_ENCODING, 'gzip')
> curl.perform()

> curl.getinfo(curl_cffi.CurlInfo.SIZE_DOWNLOAD_T)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.12/site-packages/curl_cffi/curl.py", line 243, in getinfo
    c_value = ffi.new(ret_option[option & 0xF00000])
                      ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 6291456
```
Some more insight
```python
> from curl_cffi._wrapper import ffi, lib
> ffi.getctype("long")
'long'
> ffi.getctype("char")
'char'
> ffi.getctype("curl_off_t")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ffi.error: undefined type name
curl_off_t
```

**Expected behavior**
CurlInfo options can be retrieved via `Curl.getinfo`

**Versions**
 - OS: linux x64
 - certifi==2024.8.30
 - cffi==1.17.1
 - curl_cffi==0.7.2
 - pycparser==2.22
 - typing_extensions==4.12.2

**Comment by lexiforest** [comment]
To expose the `curl_off_t` type, we need to include `typedef`s from `curl/system.h` in `ffi.cdef()`.

**Comment by usedev** [comment]
curl_off_t looks like a long

`curl.getinfo(curl_cffi.CurlInfo.SIZE_DOWNLOAD_T)
ret_option = {
    0x100000: "char**",
    0x200000: "long*",
    0x300000: "double*",
    0x400000: "struct curl_slist **",
    0x500000: "long*",
    0x600000: "long*"
}
ret_cast_option = {
    0x100000: ffi.string,
    0x200000: int,
    0x300000: float,
    0x500000: int,
    0x600000: int,
}`

**Comment by lexiforest** [comment]
I tried to add the `typedef` to `cdef`, but it does not work as documented, perhaps it's the more realistic way to do this.

> curl_off_t looks like a long
> 
> ```
> curl.getinfo(curl_cffi.CurlInfo.SIZE_DOWNLOAD_T)
> ret_option = {
>     0x100000: "char**",
>     0x200000: "long*",
>     0x300000: "double*",
>     0x400000: "struct curl_slist **",
>     0x500000: "long*",
>     0x600000: "long*"
> }
> ret_cast_option = {
>     0x100000: ffi.string,
>     0x200000: int,
>     0x300000: float,
>     0x500000: int,
>     0x600000: int,
> }
> ```

**Comment by mon** [comment]
`curl_off_t` is 64 bits, so it should be a `long long` to guarantee it's big enough. When that change is made, it works correctly on my platform (to retrieve the various `_TIME_T` opts).

**Comment by lexiforest** [comment]
Just merged #481, I think it's safe to use `int64_t` in 2025, which is more explicit.
