### ISSUE TITLE
Support response.raw

### ISSUE THREAD

**Issue by xyb** [lexiforest/curl_cffi#438]
**Is your feature request related to a problem? Please describe.**
While developing a plugin for HTTPie, I noticed that the `requests` library interface lacked access to the `response.raw` attribute, which HTTPie requires.

**Describe the solution you'd like**
```python
>>> from curl_cffi.requests import Session
>>> with Session(impersonate="chrome") as session:
...   response = session.get("https://httpbin.org/get")
...   print(response.raw)
...
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
AttributeError: 'Response' object has no attribute 'raw'

>>> from requests import Session
>>> with Session() as session:
...   response = session.get("https://httpbin.org/get")
...   print(response.raw)
...
<urllib3.response.HTTPResponse object at 0x103a09c30>
```

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by xyb** [comment]
I’ve uploaded my plugin to demonstrate how to reproduce the issue:
```sh
❯ httpie --debug plugins install httpie-curl-cffi

❯ http --debug https://httpbin.org/get
...
http: error: AttributeError: 'Response' object has no attribute 'raw'


Traceback (most recent call last):
  File "/Users/xyb/.virtualenvs/httpie-curl-cffi/bin/http", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/xyb/.virtualenvs/httpie-curl-cffi/lib/python3.11/site-packages/httpie/__main__.py", line 9, in main
    exit_status = main()
                  ^^^^^^
  File "/Users/xyb/.virtualenvs/httpie-curl-cffi/lib/python3.11/site-packages/httpie/core.py", line 162, in main
    return raw_main(
           ^^^^^^^^^
  File "/Users/xyb/.virtualenvs/httpie-curl-cffi/lib/python3.11/site-packages/httpie/core.py", line 140, in raw_main
    handle_generic_error(e)
  File "/Users/xyb/.virtualenvs/httpie-curl-cffi/lib/python3.11/site-packages/httpie/core.py", line 100, in raw_main
    exit_status = main_program(
                  ^^^^^^^^^^^^^
  File "/Users/xyb/.virtualenvs/httpie-curl-cffi/lib/python3.11/site-packages/httpie/core.py", line 213, in program
    for message in messages:
  File "/Users/xyb/.virtualenvs/httpie-curl-cffi/lib/python3.11/site-packages/httpie/client.py", line 114, in collect_messages
    response = requests_session.send(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xyb/.virtualenvs/httpie-curl-cffi/lib/python3.11/site-packages/requests/sessions.py", line 718, in send
    extract_cookies_to_jar(self.cookies, request, r.raw)
                                                  ^^^^^
AttributeError: 'Response' object has no attribute 'raw'
```

**Comment by lexiforest** [comment]
It may be possible with [`curl_easy_recv`](https://curl.se/libcurl/c/curl_easy_recv.html), but that would take a significant amount of work, let's keep this open and revisit this in the future.

**Comment by xyb** [comment]
> 
Unfortunately, it's not possible to implement this attribute. curl/libcurl will automatically unzip the response in the streaming callback no matter what, whereas response.raw should return the streaming content of the raw i.e. compressed content.

As shown in the previous example, `response.raw` is an instance of `<urllib3.response.HTTPResponse object at 0x103a09c30>`. However, implementing `response.raw` directly may not be the best solution. It would be more effective to trace the call stack and find the most appropriate entry point for addressing the issue. Unfortunately, this approach requires a deeper dive into the requests library, which I am unable to dedicate time to at the moment.

**Comment by lexiforest** [comment]
Hi, I just took another look at your stacktrace, it seems that what is missing here is `requests.Session.send()`, not `response.raw()`, now the problem is simpler to solve.

**Comment by ligix** [comment]
I came across a situation where I needed access via a file like object to the (decoded) contents of the response.

Below is the wrapper class I used with complete type hints (with only read implemented as that's the only method I needed).

<details>
<summary>response_to_file_like.py</summary>

```python
from curl_cffi import requests
from typing import BinaryIO, IO, Iterable, Iterator
from collections.abc import Buffer

ReadableBuffer = Buffer | bytes


class ResponseToFileLike(BinaryIO):
    def __init__(self, response: requests.Response, chunk_size: int|None=512) -> None:
        self.response = response
        self.data_iterable: Iterator[bytes] = response.iter_content(chunk_size=chunk_size)
        self.extra_data = bytearray()

    def __enter__(self):
        raise NotImplementedError

    def close(self):
        raise NotImplementedError

    def fileno(self):
        raise NotImplementedError

    def flush(self):
        raise NotImplementedError

    def isatty(self):
        raise NotImplementedError

    def read(self, n: int|None=-1, /):
        # file object says that binary files are two of the categories of file objects
        # binary file says that an implementation of binary file is io.Bytes.IO
        # io.BytesIO documents this behaviour
        # https://docs.python.org/3/glossary.html#term-file-object
        # https://docs.python.org/3/glossary.html#term-binary-file
        # https://docs.python.org/3/library/io.html#io.BufferedIOBase.read
        if n is None:
            n=-1

        needed_data = n - len(self.extra_data)

        try:
            while needed_data > 0 or n<0:
                needed_data -= len(c := next(self.data_iterable))
                self.extra_data.extend(c)
        except StopIteration:
            pass

        ret, self.extra_data = self.extra_data[:n], self.extra_data[n:]
        return bytes(ret)

    def readable(self):
        raise NotImplementedError

    def readline(self, limit=-1, /):
        raise NotImplementedError

    def readlines(self, hint=-1, /):
        raise NotImplementedError

    def seek(self, offset, whence=0, /):
        raise NotImplementedError

    def seekable(self):
        raise NotImplementedError

    def tell(self):
        raise NotImplementedError

    def truncate(self, size=None, /):
        raise NotImplementedError

    def writable(self):
        raise NotImplementedError

    def write(self: IO[bytes], s: ReadableBuffer, /) -> int:
        raise NotImplementedError

    def writelines(self: IO[bytes], lines: Iterable[ReadableBuffer], /) -> None:
        raise NotImplementedError

    def __next__(self):
        raise NotImplementedError

    def __iter__(self):
        raise NotImplementedError

    def __exit__(self, type, value, traceback, /):
        raise NotImplementedError
```
</details>

**Comment by ligix** [comment]
> I came across a situation where I needed access via a file like object to the (decoded) contents of the response.
> 
> Below is the wrapper class I used with complete type hints (only read, close and the ability to use it as a context manager is implemented since I didn't need more than that).
> response_to_file_like.py

If you've been using this, sorry, it truncates the last byte of the response :)
read should be implemented as:
<details>
<summary>code</summary>

```python
    def read(self, n: int | None = -1, /) -> bytes:
        # file object says that binary files are two of the categories of file objects
        # binary file says that an implementation of binary file is io.Bytes.IO
        # io.BytesIO documents this behaviour
        # https://docs.python.org/3/glossary.html#term-file-object
        # https://docs.python.org/3/glossary.html#term-binary-file
        # https://docs.python.org/3/library/io.html#io.BufferedIOBase.read
        if n is None:
            n = -1

        needed_data = n - len(self.extra_data)

        try:
            while needed_data > 0 or n < 0:
                needed_data -= len(c := next(self.data_iterable))
                self.extra_data.extend(c)
        except StopIteration:
            pass

        if n < 0:
            ret, self.extra_data = self.extra_data, bytearray()
        else:
            ret, self.extra_data = self.extra_data[:n], self.extra_data[n:]
        return bytes(ret)
```
</details>

**Comment by vivodi** [comment]
> Sorry, I have been misleading on this. libcurl actually has option to set this, as what I discovered in [lexiforest/curl-impersonate#93](https://github.com/lexiforest/curl-impersonate/issues/93)

Are there any blockers remaining for this issue?

**Comment by lexiforest** [comment]
> > Sorry, I have been misleading on this. libcurl actually has option to set this, as what I discovered in [lexiforest/curl-impersonate#93](https://github.com/lexiforest/curl-impersonate/issues/93)
> 
> Are there any blockers remaining for this issue?

No blockers, but it's a big effort. By supporting response.raw, we will be abandoning the prefect zstd/brotoli decoding embedded in curl-impersonate, and will have to add python side dependencies.
