### ISSUE TITLE
ERROR  

### ISSUE THREAD

**Issue by wuliao6688** [lexiforest/curl_cffi#461]
Traceback (most recent call last):
  File "/www/wwwroot/过检执行/.venv/lib/python3.12/site-packages/gevent/threadpool.py", line 173, in __run_task
    thread_result.set(func(*args, **kwargs))
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/过检执行/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 294, in perform
    self._check_error(ret, "perform")
  File "/www/wwwroot/过检执行/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 137, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Operation timed out after 45002 milliseconds with 76759 out of 99600 bytes received. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
2024-12-16T19:05:33Z (<ThreadPoolWorker at 0x72528bdda940 thread_ident=0x725278c006c0 threadpool-hub=<Hub at 0x72529210cc70 thread_ident=0x7252925d0080>>, <bound method Curl.perform of <curl_cffi.curl.Curl object at 0x72528c1b1e80>>) failed with CurlError

**Comment by perklet** [comment]
Please follow the issue template.
