### ISSUE TITLE
curl_cffi will report an error when used with gevent

### ISSUE THREAD

**Issue by wuliao6688** [lexiforest/curl_cffi#462]
Describe the bug

curl_cffi will report an error when used with gevent, Error messages appear from time to time

Error message content

```
Traceback (most recent call last):
  File "/www/wwwroot/过检执行/.venv/lib/python3.12/site-packages/gevent/threadpool.py", line 173, in __run_task
    thread_result.set(func(*args, **kwargs))
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/过检执行/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 294, in perform
    self._check_error(ret, "perform")
  File "/www/wwwroot/过检执行/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 137, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (16) . See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
2024-12-16T17:22:24Z (<ThreadPoolWorker at 0x72528c106f00 thread_ident=0x72527be006c0 threadpool-hub=<Hub at 0x72529210cc70 thread_ident=0x7252925d0080>>, <bound method Curl.perform of <curl_cffi.curl.Curl object at 0x72528c1602f0>>) failed with CurlError
```

```py
from gevent import monkey
monkey.patch_all()
import gevent

class CaptchaClass:
    def __init__(self, task_json):
        self.version = random.choice(["chrome", "chrome131", "Safari15_3", "Safari15_5", "Safari17_0", "safari17_2_ios", "safari18_0", "safari18_0_ios"])
        self.Client = requests.Session(thread="gevent", verify=False, timeout=35, impersonate=self.version)
```

**Versions**
 - OS: Windows 10
 - curl_cffi version: 0.8.0b7
 - pip freeze dump [requirements.txt](https://github.com/user-attachments/files/18161197/requirements.txt)

**Additional context**
- Which session are you using? async or sync?
- If using async session, which loop implementation are you using?
- If you have tried, does this work with other http clients, e.g. `requests`, `httpx` or real browsers.

**Comment by lexiforest** [comment]
Please provide a REPRODUCIBLE code snippet, not a random snippet from your codebase. Creating nonsense issues repeatedly will be banned from this project.

Are you using threading with Session? You can try creating one session per thread.

Also, using random.choice to select an impersonate target is an anti-pattern, especially when mixing chrome and safari versions.
